### ISSUE TITLE
Android compilation time warning

### ISSUE THREAD

**Issue by ivanovpv** [jorabin/KeePassJava2#14]
Gradle reports:

>Warning:WARNING: Dependency xpp3:xpp3:1.1.3.3 is ignored for %project_name% as it may be conflicting with the internal version provided by Android.

**Comment by jorabin** [comment]
Hey Pavel - As discussed by email I believe this is because the **jaxb** module is not suitable for Android. If you use the **all** module as a dependency **jaxb** is pulled in as a transitive dependency. The **all** module should not really be used except if you want to do comparisons between the various kdbx implementations. In your case suggest adding **kdb** and **simple** as dependencies directly.

@ivanovpv Would you confirm, please, that this solves your problem? I think the README could be clarified to make it clear that you rarely should use the **all** module and I'll close this issue once I've done that.

**Comment by ivanovpv** [comment]
Yes, you're righteous. To support kdbx one need to import either **simple** or **dom** modules
